### PR TITLE
Add language link

### PR DESCRIPTION
**Pull request by suzumaze**
Adding link to the [Japanese version of the site](https://qiqphp-ja.github.io/).
The same navigation will be added to the Japanese version of the site so that users can go back and forth.

### CODE REVIEW

**Comment by koriym** [comment]
Looks good to me.

**Comment by koriym** [comment]
The link on the top right is the language selection link.

image

**Comment by koriym** [comment]
@pmjones Gentle reminder

**Comment by pmjones** [comment]
Sorry @koriym -- thanks for your patience.

**Comment by koriym** [comment]
We recently released the website of "Spur", a leading mode magazine in Japan. All pages are rendered in Qiq.
https://spur.hpplus.jp/

It is a switch from Twig, All of us prefer Qiq over Twig and will continue to use it.

**Comment by koriym** [comment]
Thank you for the great software!

**Comment by pmjones** [comment]
Oh @koriym that is *so* great to hear -- thanks !!!

**Pull request merged**
